project: 
  type: website
  output-dir: docs

website:
  title: "Cameron Playle Data Analysis Portfolio"
  navbar:
    left: 
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "UTSA Trackman Data"
            file: utsa-baseball-analysis/utsa-baseball-analysis.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
          - text: "Tidy Tuesday Exercise"
            file: tidytuesday-exercise/tidytuesday-exercise.qmd
          - text: "Tidy Tuesday Exercise #4"
            file: data-exercise/data-exercise.qmd
          - text: "Assignment #5: Processing Data"
            file: cdcdata-exercise/cdcdata-exercise.qmd
          - text: "Machine Learning Project"
            file: machine-learning-project/MachineLearningProject.qmd
          - text: "Tommy John Project"
            file: Tommy-John-Project/tommy-john-project.qmd
            
    right:
      - icon: github 
        href: https://github.com/cameronplayle/CameronPlayle-P2-Portfolio.git        

format:
  html:
    theme: superhero
    highlight: zenburn
    css: styles.css
    toc: FALSE


